#cloud-config
hostname: ${hostname}
users:
  - name: ${admin}
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    passwd: ${admin_passwd}
    lock_passwd: false
    ssh_authorized_keys:
      - ${admin_key}

write_files:
  - path: /opt/cache/install_apt_cacher_ng.sh
    permissions: '0755'
    encoding: b64
    content: |
      ${install_apt_cacher_ng_script}
  - path: /opt/cache/install_squid_deb_proxy.sh
    permissions: '0755'
    encoding: b64
    content: |
      ${install_squid_deb_proxy_script}
  - path: /opt/cache/install_ssl_squid_proxy.sh
    permissions: '0755'
    encoding: b64
    content: |
      ${install_ssl_squid_proxy_script}
  - path: /opt/cache/squid.conf
    permissions: '0644'
    encoding: b64
    content: |
      ${squid_conf}

runcmd:
  - echo ${address} ${hostname} >> /etc/hosts
  - /opt/cache/install_ssl_squid_proxy.sh