#!/bin/bash
apt update && apt install -y qemu-guest-agent squid-deb-proxy
systemctl enable qemu-guest-agent
systemctl start qemu-guest-agent
ufw allow 8000/tcp
cp /etc/squid-deb-proxy/allowed-networks-src.acl /etc/squid-deb-proxy/autogenerated
sed -i -E "s/(http_access\ deny\ \!to_archive_mirrors)/#\1/" /etc/squid-deb-proxy/squid-deb-proxy.conf
sed -i -E "s/(cache\ deny\ \!to_archive_mirrors)/#\1/" /etc/squid-deb-proxy/squid-deb-proxy.conf
systemctl restart squid-deb-proxy