version: "3"

services:
  openldap:
    image: openldap
    ports:
      - "389:389"
      - "636:636"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/opt/openldap/data
      - ./certs:/opt/openldap/certs