version: "3"

services:
  openldap:
    image: openldap
    hostname: ${hostname}
    ports:
      - "389:389"
      - "636:636"
    extra_hosts:
      - ${hostname}:127.0.0.1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - HOSTNAME=${hostname}
      extra_hosts:
        - ${hostname}:127.0.0.1