#cloud-config
hostname: ${hostname}
users:
  - name: ${username} 
    ssh_authorized_keys:
      - ${ssh_key}
      - ${k8s_admin_ssh_public_key}
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
    lock_passwd: true

growpart:
  mode: auto
  devices: ['/']
      
write_files:
  - path: /opt/k8setup/init.sh
    permissions: '0755'
    encoding: b64
    content: |
      ${init_script}
  - path: /opt/k8setup/install_crio.sh
    permissions: '0755'
    encoding: b64
    content: |
      ${install_crio_script}
  - path: /opt/k8setup/install_kube.sh
    permissions: '0755'
    encoding: b64
    content: |
      ${install_kube_script}
  - path: /opt/k8setup/hosts
    permissions: '0755'
    encoding: b64
    content: |
      ${hosts}
  - path: /opt/k8setup/cluster_endpoint_hostfile
    permissions: '0755'
    encoding: b64
    content: |
      ${cluster_endpoint_hostfile}     
  - path: /opt/k8setup/concat_hostname.sh
    permissions: '0755'
    encoding: b64
    content: |
      ${concat_hostname_script}
  - path: /opt/k8setup/install_containerd.sh
    permissions: '0755'
    encoding: b64
    content: |
      ${install_containerd_script}
  - path: /opt/k8setup/install_containerd_cni.sh
    permissions: '0755'
    encoding: b64
    content: |
      ${install_containerd_cni_script}
  - path: /opt/k8setup/configure_proxy.sh
    permissions: '0755'
    encoding: b64
    content: |
      ${configure_proxy_script}
  - path: /opt/k8setup/wait.sh
    permissions: '0755'
    encoding: b64
    content: |
      ${wait_script}
  - path: /etc/apt/apt.conf.d/custom-apt.conf
    permissions: '0755'
    encoding: b64
    content: |
      ${custom_apt_conf}
  - path: /opt/k8setup/install_nfs_server.sh
    permissions: '0755'
    encoding: b64
    content: |
      ${install_nfs_server_script}      
  - path: /opt/k8setup/configure_nfs_nodes.sh
    permissions: '0755'
    encoding: b64
    content: |
      ${configure_nfs_nodes_script}

runcmd:
  - echo "\n" | cat /opt/k8setup/hosts - >> /etc/hosts
  - echo "\n${nfs_server_ip} ${nfs_server_hostname}" >> /etc/hosts
  - /opt/k8setup/configure_proxy.sh ${proxy_server}
  - apt update && apt install -y qemu-guest-agent
  - systemctl start qemu-guest-agent
  - systemctl enable qemu-guest-agent
  - chown -R ${username}:${username} /home/${username}
  - /opt/k8setup/concat_hostname.sh
  - /opt/k8setup/init.sh
  - /opt/k8setup/install_crio.sh
  - /opt/k8setup/install_kube.sh ${kube_version} ${username}
  - /opt/k8setup/configure_nfs_nodes.sh
  - touch /opt/k8setup/done.txt
