version: 2
ethernets:
    ens3:
        dhcp4: false
        addresses:
            - ${management_ip}/24
        gateway4: ${management_gateway}
        nameservers:
            addresses:
            - ${management_dns}
    ens4:
        addresses:
            - ${provider_ip}/24
        gateway4: ${provider_gateway}
        nameservers:
            addresses:
                - ${provider_dns}