version: 2
ethernets:
    ens3:
        dhcp4: false
        addresses:
            - ${management_ip}/${management_prefix}
        gateway4: ${management_gateway}
        nameservers:
            addresses:
            - ${management_dns}